### ISSUE TITLE
Startup script/restart policy documentation

### ISSUE THREAD

**Issue by grigorye** [cirruslabs/orchard#101]
It's not an issue, rather more of a question: do I get it correctly, that if *startup script* fails, the corresponding vm (with restart policy "OnFailure") would get "restarted"?

**Comment by edigaryev** [comment]
Yes, the startup script failure results in VM changing it's state to `failed`.

`failed` VMs will get re-scheduled (with the same settings as they've been instantiated, but possibly on another worker) if their restart policy is set to `OnFailure`.
