### ISSUE TITLE
VM UID name generation improvement

### ISSUE THREAD

**Issue by ruimarinho** [cirruslabs/orchard#116]
Hi,

When launching a new VM, orchard generates a UID to avoid data races, but I think could be more interesting to include the VM Meta name as part of the of UID, i.e., prepending the name before the UID.

This would give a more visual cue while troubleshooting.

What do you think?

**Comment by edigaryev** [comment]
Hello Rui,

Can you explain a bit where do you want to see the VM's name: in `tart list` output (it's already there) or somewhere else?

**Comment by ruimarinho** [comment]
Hi @edigaryev,

I was referring to this header:

<img width="904" alt="image" src="https://github.com/cirruslabs/orchard/assets/288709/93c1560d-b44f-456f-a60b-204b01ba5639">

I've come to realize that the name (in this case, the name is an ULID) is indeed being prepended to the built-in UID, so I'm closing this issue. Apologies for the confusion.
