### ISSUE TITLE
`orchard list vms` should include the worker where the VM is running at

### ISSUE THREAD

**Issue by ruimarinho** [cirruslabs/orchard#132]
Hi,

I think it would be super useful to show the worker where each VM is running at on the `orchard list vms`, even if this requires a new command line argument. Another option would be to hide everything related to "policies" by default.

To troubleshooting dying VMs, sometimes a direct connection to the worker is needed.

**Comment by edigaryev** [comment]
This was just implemented in https://github.com/cirruslabs/orchard/pull/139 (https://github.com/cirruslabs/orchard/pull/139/commits/556cfff872d87a8a4fe4e915ac82a2e76ca33d8d).
