### ISSUE TITLE
Support for Tart 2.0

### ISSUE THREAD

**Issue by ruimarinho** [cirruslabs/orchard#137]
Hi,

Is Orchard fully compatible with Tart 2.0? It seems to depend on the binary executable rather than embedding its client and the API seems to have remain unchanged, but wanted to check before proceeding with the upgrade.

Thanks!

**Comment by fkorotkov** [comment]
You should be all good to go. There were no changes in the CLI arguments. Tart 2.0.0 mostly brings Sonoma goodies and an improved format for storing images remotely in OCI registries. Please check out [this blog post](https://tart.run/blog/2023/09/20/tart-200-and-community-updates/) if you haven't already.
