### ISSUE TITLE
Binding host ports to VMs

### ISSUE THREAD

**Issue by stevepentland** [cirruslabs/orchard#156]
Hi there, I'm attempting to deploy an application in a VM that will expect to receive communications from other machines on our network. While outbound communications back to other machines in our infrastructure work, communication to the application within the VM do not seem possible. I have been trying to find something in the docs for tart & orchard that will help me understand how to enable this but have not had any success. Is there just some simple thing I'm missing to bind a port from the host to the VM? I've tried both the default & bridged networking types with no real success so far. The host machines do not have any additional firewall rules enabled that would interfere either.

**Comment by edigaryev** [comment]
As far as I know there's no such functionality in the [`Virtualization.Framework`](https://developer.apple.com/documentation/virtualization) except for the bridged interfaces, which is already available in Tart via `--net-bridged` command-line argument to `tart run`. Have you considered using it?

Also, there's a [port-forwarding functionality in `vmnet.framework`](https://developer.apple.com/documentation/vmnet/vmnet_interface_add_port_forwarding_rule(_:_:_:_:_:_:)), which is closely related to `Virtualization.Framework`, but unfortunately it was not exposed in the latter. Consider [reporting this to Apple](https://developer.apple.com/bug-reporting/).

**Comment by edigaryev** [comment]
Hello Steve 👋 

>I've tried both the default & bridged networking types with no real success so far.

Could you provide some details on how did you configure the bridged networking, and how did you test it?

For me it works just fine when creating a VM using `orchard create vm --net-bridged=en0` and then connecting to the IP that was assigned to the VM (I test this by starting a HTTP server on the VM with `python3 -m http.server 8080` and then opening `http://<VM IP>:8080/` in the browser).

**Comment by edigaryev** [comment]
Closing because of no reply.
