### ISSUE TITLE
backup service accounts

### ISSUE THREAD

**Issue by eecsmap** [cirruslabs/orchard#173]
I am running an Orchard cluster in my prod env. I would like to backup / restore my service accounts in case of any system failure.
What is the best way to do this? Or I should just copy and backup the whole ~/.orchard/ folder?

**Comment by edigaryev** [comment]
> Or I should just copy and backup the whole ~/.orchard/ folder?

Unfortunately we don't have a dedicated backup mechanism at the moment, so pretty much this.

And to be completely precise, you need the `~/.orchard/controller` directory, which contains controller's X.509 certificate and the database (in [BadgerDB](https://github.com/dgraph-io/badger) format).
