### ISSUE TITLE
Running other containers 

### ISSUE THREAD

**Issue by rahb3rt** [cirruslabs/orchard#175]
Maybe I dont fully understand how OCI works or what the best method is for this. I was curious though, if I wanted to make a deployment using something like Postgres within orchard is this possible? So a linux/postgres image? Is there anything special I would need to do this?

**Comment by edigaryev** [comment]
> I was curious though, if I wanted to make a deployment using something like Postgres within orchard is this possible?

Unfortunately this is not possible, please see https://tart.run/integrations/vm-management/#working-with-a-remote-oci-container-registry:

>Tart supports interacting with Open Container Initiative (OCI) registries, but only runs images created and pushed by Tart. This means images created for container engines, like Docker, can't be pulled. Instead, create a custom image as documented above.
