### ISSUE TITLE
Orchard worker failing to add itself to controller

### ISSUE THREAD

**Issue by PrashantRaj18198** [cirruslabs/orchard#177]
Orchard worker is not able to register itself on the controller. It's saying

```
{"level":"warn","ts":1716178426.195953,"caller":"worker/worker.go:105","msg":"failed to register worker: API client encountered an API error to make a request: 409 Conflict (this worker is managed from a different machine ID, delete this worker first to be able to re-create it)"}
```

Is there a way to override the name of the worker?

**Comment by edigaryev** [comment]
>this worker is managed from a different machine ID, delete this worker first to be able to re-create it

This is a safety mechanism to prevent two workers from updating on a single Worker resource in the API.

>Is there a way to override the name of the worker?

Now there is: https://github.com/cirruslabs/orchard/pull/210.
