### ISSUE TITLE
Missing 0.19.1 image

### ISSUE THREAD

**Issue by ruimarinho** [cirruslabs/orchard#183]
Hi,

Could you please push version 0.19.1 to the registry? It's missing at the moment.

Many thanks!

**Comment by edigaryev** [comment]
Hi! 👋 Sorry for the hiccup.

We've been trying to run tests on the new macOS Sequoia and unfortunately things don't seem to be ready yet for CI.

I've just deleted both the 0.19.1 release and the associated tag, will make a new release once we fix this.

**Comment by ruimarinho** [comment]
Thank you for the feedback! Running 0.19.1 now :) cheers.
