### ISSUE TITLE
What is the best way to backup Orchard settings?

### ISSUE THREAD

**Issue by eecsmap** [cirruslabs/orchard#195]
I am trying to figure out how to backup the tokens I created for different roles. Do you have any suggestion?

**Comment by edigaryev** [comment]
I think this was already answered in https://github.com/cirruslabs/orchard/issues/173#issuecomment-2098162149.

Have you had a chance to try this approach?

**Comment by eecsmap** [comment]
Holy.. Man, I got really bad memory! Sorry I duplicated the question.
I now shift to Google Kubernetes Engine and use persistentVolume to store this folder now:)
