### ISSUE TITLE
Can we group workers

### ISSUE THREAD

**Issue by eecsmap** [cirruslabs/orchard#196]
We have some workers setup with 2vms capacity to run normal tasks. But we want to set some other workers with 1vm to run heavy tasks which takes more CPUs and RAMs. I wonder do we have a way to target the different group of workers for different requests?

**Comment by edigaryev** [comment]
You can achieve this with [resource management](https://github.com/cirruslabs/orchard/blob/main/IntegrationGuide.md#resource-management), which already defines a useful resource named `org.cirruslabs.tart-vms`.

Simply pass `--resources org.cirruslabs.tart-vms=1.0` for small VMs and `--resources org.cirruslabs.tart-vms=2.0` for large VMs when doing `orchard create vm`.

This will cause the scheduler to only schedule two normal VMs or one heavy VM on a given worker.
