### ISSUE TITLE
Docker:  exec: "/bin/orchard": stat /bin/orchard: no such file or directory: unknown.

### ISSUE THREAD

**Issue by mcmarkj** [cirruslabs/orchard#205]
Hiya,

I believe that https://github.com/cirruslabs/orchard/commit/32f2d17c13ca7ef92839f51c9c598b7afdfed1bc may have broken the docker images. 

```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/orchard": stat /bin/orchard: no such file or directory: unknown.
```

Any suggestions, perhaps I'm doing something wrong?

**Comment by edigaryev** [comment]
Hi, thanks for reporting and sorry for the hiccup!

This should now be fixed in the latest `ghcr.io/cirruslabs/orchard:0.23.1` image.
