### ISSUE TITLE
Get a summary of jobs done in a given period of time.

### ISSUE THREAD

**Issue by eecsmap** [cirruslabs/orchard#206]
Hi Orchard guys :)

I am running the orchard service for couple of months and I have been asked what value this service bring to the team. Well, the easiest way to tell is to show how many real build job finished in a day/week/month. I am thinking about getting this information out of the deleting event of each VM. So whenever there is a VM to be delete. We report the scheduling time, execution time and period, together with the VM name somewhere. Maybe via the OpenTelemetry log so we can parse the logs? Any idea?

**Comment by edigaryev** [comment]
Hi @eecsmap!

We could probably just emit such events to the standard output in JSON format from the controller, would that work for you?

**Comment by eecsmap** [comment]
@

> Hi @eecsmap!
> 
> We could probably just emit such events to the standard output in JSON format from the controller, would that work for you?

Log from controller should be fine, as long as I can get the log in the OTP log in google cloud.

**Comment by edigaryev** [comment]
Please check out the [new `0.24.0` release](https://github.com/cirruslabs/orchard/releases/tag/0.24.0), in which the Controller now logs the VM lifecycle events when the VM gets deleted or restarted.
