### ISSUE TITLE
Curl hang on querying VM IP

### ISSUE THREAD

**Issue by eecsmap** [cirruslabs/orchard#218]
Recently I am working on a service heavily relying on the API /vms/{vmname}/ip. Yet I have run into couple of times that the query simply hangs.

```
user@host-01 ~ % oc -v  https://orchard.mycompany.net/v1/vms/testvm/ip
* Host orchard.mycompany.net:443 was resolved.
* IPv6: (none)
* IPv4: 10.0.0.11
*   Trying 10.0.0.11:443...
* Connected to orchard.mycompany.net (10.0.0.11) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256 / [blank] / UNDEF
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: C=US; ST=California; L=Palo Alto; O=MyCompany Inc.; CN=*.mycompany.net
*  start date: Apr 10 00:00:00 2024 GMT
*  expire date: Apr 10 23:59:59 2025 GMT
*  subjectAltName: host "orchard.mycompany.net" matched cert's "*.mycompany.net"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* using HTTP/1.x
* Server auth using Basic with user 'orchard-root'
> GET /v1/vms/testvm/ip HTTP/1.1
> Host: orchard.mycompany.net
> Authorization: Basic xxxxxxxxxxxxxxxxxxx
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
```
Then it hangs.

This issue is not observed on my prod environment. Yet happens in my test environment with a large chance. Any suggestion?

**Comment by eecsmap** [comment]
It seems hang on waiting for https://github.com/cirruslabs/orchard/blob/main/internal/controller/api_vms_ip.go#L58

**Comment by edigaryev** [comment]
Hello!

1. Are these hangs reproducible for a short period of time after a single hang occurs, or they're completely stray with only a single one occurring in a minute/hour/day timeframe?

1. Are you using `--net-bridged`? Using `--net-bridged` causes Orchard to pass `--resolver=arp` to the `tart ip` command, which in turn relies on the VM being active on the local network to populate the host's ARP table.

    Most Linux VMs [don't do that out-of-the box](https://github.com/cirruslabs/tart/issues/873#issuecomment-2252626698) and this happens sometimes with long-running macOS VMs.

1. The next time you observe this, could you please verify that `tart ip orchard-<VM-name>-<UUID>` (or `tart ip --resolver=arp orchard-<VM-name>-<UUID>` when using `--net-bridged`) works on the node with your VM at the time this happens?

**Comment by eecsmap** [comment]
When I run `tart ip <vmname>` I got `no IP address found`
When I run `tart ip <vmname> --resolver=arp` I also got `no IP address found`

I double checked with the DHCP server and it actually allocate the IP for the MAC of the VM. I can ssh into the VM using this IP.

**Comment by eecsmap** [comment]
I think I got the problem fixed. Thanks!

**Comment by Formartha** [comment]
I'm having the same issue, 
when running a machine using orchard, I'm able to see that the worker opened the machine, I can manually (using tart) see it's internals but I can't resolve it's IP address.

I'm using bridged mode as it needs to communicate with external systems.

What have you done to resolve it?

<img width="977" alt="Image" src="https://github.com/user-attachments/assets/456bea39-e6b0-4791-80d4-a166aa8c7cf3" />

**Comment by edigaryev** [comment]
@Formartha please see [Resolving the VM's IP when using bridged networking](https://tart.run/faq/#resolving-the-vms-ip-when-using-bridged-networking).

**Comment by Formartha** [comment]
Gothca. @edigaryev 
One more Q: can we have more than one VM running at the same host machine which uses bridged adapter on the same interface?

**Comment by edigaryev** [comment]
>One more Q: can we have more than one VM running at the same host machine which uses bridged adapter on the same interface?

Yes, you can.

**Comment by edigaryev** [comment]
> I still am unable to understand how to solve the ip resolution even after installing samba on the orchard manager.

Please see https://github.com/cirruslabs/tart/issues/1020.

The problem is that a second VM gets ignored by the host's NBNS resolver because it has the same name as the first VM.

Would you mind explaining the reason for using the `--net-bridged` in the first place? Perhaps there are other ways to accomplish this?

**Comment by Formartha** [comment]
Thanks @edigaryev 

We have a product which uses orchestrator and agents. The orchestrator is an instance (service) in AWS and it connects to a local machine and instals an agent on. The remote orchestrator and the agent share data between them and the connection is being done two ways.

Without bridge I won't be able to do it, as far as I tried.

Also,
to be able to install the agent, we'd need (as a part of deployment flow) to access the VM and run a set of commands which will fetch and deploy the agent on the newly created VM. This is a part of a CI process I'm aiming to introduce.

**Comment by edigaryev** [comment]
Just to clarify: do you only need the ability to e.g. SSH to the VM to configure the agent?

Or your orchestrator also needs to be able to reach agent's TCP/UDP port on that VM?

**Comment by Formartha** [comment]
I’d need both.
1. Installing the agent will require a ssh connection 
2. Using the orchestrator and the agent in a call flow will require TCP connection between them

**Comment by edigaryev** [comment]
>will require TCP connection between them

And the initiator will be the controller? Or the agent? Or both?

Note that in case it'll be the agent who initiates the connect, you don't need bridged networking.

**Comment by Formartha** [comment]
Great question. There are two use cases:
1. The agent polls a bucket in the orchestrator to determine if there is a new task ready
2. 2. The orchestrator calls the agent to query its status and perform administrative tasks (upgrade, restarts etc.)

So to answer your question, both initiate the connection.

**Comment by edigaryev** [comment]
> So to answer your question, both initiate the connection.

Thanks for the clarification.

Back to `--net-bridged`: do I understand correctly that it's only an issue for you when using Linux VMs?

If so, I'll try to prioritize the https://github.com/cirruslabs/tart/issues/1020.

**Comment by Formartha** [comment]
So the use case is as the following:
The setup is based out of one EC2 instance that runs orchard container and acts as a controller.
Two Mac minis are acting as workers and connects to the EC2 instance.

When running the command locally to get the ip of the VMs with using arp, it works.
However, when running the command using restful call to the controller, the error is listed as in the photo I attached to this thread.

I hope it helps understanding more..

**Comment by Formartha** [comment]
I’m only running Mac OS VMs, not Linux.
Maybe it’s a different issue?

**Comment by edigaryev** [comment]
>I’m only running Mac OS VMs, not Linux.
>Maybe it’s a different issue?

It's a different issue in this case.

1. Which Orchard versions are you running on the controller and workers?
2. Can you try calling the IP resolution endpoint with a higher timeout (the `wait` parameter)? E.g. 60 seconds.

**Comment by edigaryev** [comment]
>However I can see that the worker is connected and the logs indicates it (as well as calling to create a new machine works)

1. Anything fishy in the `SBLT0186.local` worker's logs?
1. Can you try starting the `orchard controller run` with [`--experimental-rpc-v2`](https://github.com/cirruslabs/orchard/releases/tag/0.27.0) command-line flag?
1. Also, do you use some kind of HTTP proxy or a load-balancer before the Orchard Controller?

**Comment by Formartha** [comment]
So it seems like you were right, the rpc call did solve the issue.
I have upgraded both the controller and the workers to the latest release and it now returns the ip address of the machines.

**Comment by edigaryev** [comment]
> Edit: it works but than fails after few tries:

What if you manually run the same command on the affected worker?

```shell
tart ip --resolver arp orchard-safebreach_mac_fd532849-6618-4d2a-94e4-1254518e5fdb-69763337-64eb-49d3-8420-b502646378ce-0
```

Another thing to understand is whether the VM gets any connectivity at all. You can pass `--headless=false` to `orchard create vm` and observe the VM's screen on the associated worker. Check "System Settings → Network → Ethernet" from within a VM to see whether it receives an IP address from the DHCP server.

And how your LAN's DHCP server look like? Is it possible that it has a small lease time, which results in address shortage?

**Comment by Formartha** [comment]
I have validated the questions:
1. manually running the command doesn't produce anything if the machine is running from some time. on a new machine it works and I don't know why (same goes for the api call).
2. the lease time is 24 hours, we don't have issues with ip addresses in this subnet at all

**Comment by Formartha** [comment]
hi @edigaryev ,
1. There is 100% connectivity from within the tart machine (i.e. I can use it to surf to githun.com for example)
2. The tart ip provides returns "no ip address found"
3. the lease time is 7d, we aren't filling the whole subnet (we have no more than 10% fill)

**Comment by edigaryev** [comment]
@Formartha 

1. Which image are you using for these VMs? If it's not [Cirrus Labs-provided image](https://tart.run/quick-start/#vm-images), can you try with a Cirrus Labs-provided one?

2. How long does it take before a VM stop being resolvable via `tart ip`?

**Comment by Formartha** [comment]
@edigaryev 

1. I'm using only Cirrus labs images.
2. I'm not sure, but it's around a day I guess.

**Comment by Formartha** [comment]
Hi @edigaryev , can you help out?

**Comment by edigaryev** [comment]
@Formartha

1. Which image are you using for these VMs? Above you've answered that you're using only Cirrus labs images, but didn't specify which one(s).

2. Which `orchard create vm` arguments are you using? E.g. `--net-bridged`, `--net-softnet`, etc.

**Comment by Formartha** [comment]
Hi @edigaryev 

1. I'm using `ghcr.io/cirruslabs/macos-sonoma-base:latest` mostly
2. I'm using API to trigger the creation of the machine, that's the payload I'm using:
`{
            "name": name,
            "image": image,
            "cpu": cpu,
            "memory": memory,
            "net-bridged": net_bridged
        }
`

**Comment by edigaryev** [comment]
Thanks for the information.

> 2\. I'm using API to trigger the creation of the machine, that's the payload I'm using:

What does `net_bridged` expand to here? `true` or `false`?

**Comment by Formartha** [comment]
So it's a string which I'm filling the interface on the host VM, in that case, we're using `en0`

**Comment by Formartha** [comment]
So as far as I know, and been using, there's an API that uses resolver `/vms/{name}/ip` I'm not sure what's the difference between this and what you've suggested looking at.
At the meantime, what can I do to workaround the problem?

As currently, we are unable to use it due to this issue :(

**Comment by Formartha** [comment]
I have some sort of workaround I just need to know if there's an option to change the machine name (the hostname) during deployment. If that's an option, were good to go.
@edigaryev , can it be done?

**Comment by edigaryev** [comment]
Hello @Formartha,

Please check out the latest [Orchard `0.34.0` release](https://github.com/cirruslabs/orchard/releases/tag/0.34.0), it includes a fix for the issue that you're observing.

Note that since this change requires that your VMs are provisioned with [Guest agent for Tart VMs](https://github.com/cirruslabs/tart-guest-agent) version `0.5.0` or newer, you may need install/upgrade the agent yourself and create a [launchd unit](https://github.com/cirruslabs/macos-image-templates/blob/main/data/tart-guest-agent.plist) if not done yet by us.

Cirrus Labs-provided macOS images containing the new agent version will hopefully be available this weekend.

As for dynamically changing the hostname, this is not possible at the moment on macOS because it doesn't implement [Cloud Init](https://cloud-init.io/) or anything like that.

**Comment by Formartha** [comment]
many thanks @edigaryev !
as I'm not using lunchd unit (for some reason it's not working well on my end) I just updated the orchardcli on the host machines (the platform for spinning up vms) and a new orchard controller container. would it be enough or shall I do something else?

**Comment by Formartha** [comment]
So I'm afraid it's not working..

`automation-mac-2@SBLT0185 ~ % tart list 
Source Name                                                                                                         Disk Size SizeOnDisk State  
OCI    ghcr.io/cirruslabs/macos-sonoma-base:latest                                                                  50   29   29         stopped
OCI    ghcr.io/cirruslabs/macos-sonoma-base@sha256:d6ded80c5c259f065d7008ea9f6428f7e62f4452cc03705e065ff10261efb660 50   29   29         stopped
automation-mac-2@SBLT0185 ~ % tart list
Source Name                                                                                                         Disk Size SizeOnDisk State  
local  orchard-safebreach_mac_1088402a-ee8a-4204-934f-1f5cf77ad49e-d17bdb42-8962-4377-9357-a2d1008c9291-0           50   27   27         running
OCI    ghcr.io/cirruslabs/macos-sonoma-base:latest                                                                  50   29   29         stopped
OCI    ghcr.io/cirruslabs/macos-sonoma-base@sha256:d6ded80c5c259f065d7008ea9f6428f7e62f4452cc03705e065ff10261efb660 50   29   29         stopped
automation-mac-2@SBLT0185 ~ % tart ip orchard-safebreach_mac_1088402a-ee8a-4204-934f-1f5cf77ad49e-d17bdb42-8962-4377-9357-a2d1008c9291-0 --resolver=agent
no IP address found (also make sure that Guest agent for Tart is running inside of a VM)
automation-mac-2@SBLT0185 ~ % 
`

**Comment by edigaryev** [comment]
1. Which arguments are you passing to `tart run`?
2. What if you want for a couple of seconds after the VM boots and only then invoke `tart ip --resolver=agent`?
3. Could you please check the `/tmp/tart-guest-agent.log` contents inside of a VM after executing `tart ip --resolver=agent`?
