### ISSUE TITLE
[Potential Bug] Orchard deployments using GCP seems to fail.

### ISSUE THREAD

**Issue by PrashantRaj18198** [cirruslabs/orchard#227]
## Desc

I'm following the GCP deployment guide: https://tart.run/orchard/deploying-controller/#google-compute-engine from here. It is able to deploy the container. I can see from the GCP logs that a container was started on the VM.

But connection (create context) seems to give me an error,

```
./orchard context create --name wb-6 --service-account-name bootstrap-admin --service-account-token <redacted> https://<redacted>:443
trying to connect to the controller using PKI and host's root CA set...
PKI association failed (API client failed to make a request: Get "https://<redacted>:443/v1/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)), falling back to trusted-certificate approach...
dial tcp <redacted>:443: connect: operation timed out
```

I thought it might be something to do with vpc firewalls, so I tried with a vpc that doesn't have an firewall rules which gave me the same error. Then since pki was failing, so I tried with `--no-pki` flag as well.
```
# with --no-pki and https://
dial tcp <redacted>:443: connect: operation timed out
# with --no-pki and http://
dial tcp <redacted>:443: connect: operation timed out
```
Changing scheme seems unrelated.

Also, changing the port to `6242` and then using it with `--no-pki` (with http), gave me the following error
```
The authencity of controller <redacted>:443 cannot be established.
Certificate SHA-256 fingerprint is 10 D9 88 86 B9 E5 E6 E0 F7 0F CC E8 8A 21 14 CE 18 5E C1 9E 87 EF E4 07 70 88 CA F3 CB AB DC 93.
Are you sure you want to establish trust to this certificate? (yes/no) yes
2024/12/03 23:37:37 API client encountered an API error to make a request: 400 Bad Request
```
This makes it look like it reached the server at least since it was able to give 400 back. But not sure what I need to change here.

## System Attributes
Orchard: 0.26.0 (latest) for the server and for the client

**Comment by edigaryev** [comment]
You need to issue one more command to allow the traffic to TCP port 443:

```
gcloud compute firewall-rules create default-allow-https --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=tcp:443 --source-ranges=0.0.0.0/0 --target-tags=https-server
```

Documenting this in https://github.com/cirruslabs/tart/pull/983.
