### ISSUE TITLE
Reporting errors via Sentry from tart runs

### ISSUE THREAD

**Issue by ruimarinho** [cirruslabs/orchard#232]
Hi,

It seems like tart supports Sentry for error reporting, so I was wondering if setting an `EnvironmentVariables` block dictionary keys with `SENTRY_AUTH_TOKEN`, `SENTRY_ORG` and `SENTRY_PROJECT` would also get passed on to tart by orchard.

Thanks!

**Comment by edigaryev** [comment]
It should be possible, [similarly to how you can pass `TART_NO_AUTO_PRUNE`](https://github.com/cirruslabs/orchard/issues/229#issuecomment-2533056849).

And you [only need to pass `SENTRY_DSN`](https://github.com/cirruslabs/tart/blob/31ab4218f7ce73a40c3304db3137cb430cd53823/Sources/tart/Root.swift#L33-L51) to achieve this.

**Comment by ruimarinho** [comment]
Thanks, I’ll give it a try as there is a lot of untapped potential here :)
