### ISSUE TITLE
Command to pause/resume a worker

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/orchard#45]
Let's introduce a `orchard worker pause NAME` command which will pause scheduling on a particular worker and wait for all the VMs to get into final state if `--wait` flag is provided.

This command will be useful for gradual upgrades of workers without interraptions.

**Comment by edigaryev** [comment]
> Let's introduce a `orchard worker pause NAME` command

I think a more consistent invocation would look like `orchard pause worker NAME` since a worker is a resource and we already have things like `orchard list workers`.
