### ISSUE TITLE
More granular permissions for workers

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/orchard#54]
Right now a service account used for workers is required to have three roles: `worker` for registration and `compute:write`/`compute:read` pair for updating VMs.

`compute:*` role on the other hand gives access to all the VMs. We should probably investigate how to make authorization to resources more granular so only `worker` will allow a worker to manage compute assigned to it.

**Comment by edigaryev** [comment]
Discussed this with @fkorotkov and decided to close this for now, see https://github.com/cirruslabs/orchard/pull/77 for more details.
