### ISSUE TITLE
VMs can be left in `running` state after a worker crash

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/orchard#64]
It seems that currently, if the worker has a VM that is `running` and that worker suddenly crashes, the VM will be left in the `running` state, even after the worker comes back online.

We need to add some logic to fix that, either in the scheduler, or on the worker's side.

**Comment by fkorotkov** [comment]
I guess there are two possibilities here:

1. Worker goes offline for a long time. In this case `Scheduler` should mark such VMs as failed at some point.
2. Worker restarts and becomes available before `Scheduler` notices it was offline and VMs failed. In this case upon starting after worker registers, worker should `tart list` to find all the `orchard-*` VMs and sync them. If controller knows about local VMs than change their statuses to failed. If the VMs were deleted on the controller, then worker can just `tart delete` them locally as well.
