### ISSUE TITLE
Support for sharing files with the host system

### ISSUE THREAD

**Issue by grigorye** [cirruslabs/orchard#91]
If I get it correctly, tart has options (`--disk`, `--dir`) for running VM with files shared/defined by the host system. I can't find anything like that in orchard. I'm looking into it because I need to supply some non-trivial amount of data (basically an executable) into VM startup script (so that the executable would survive restart of VM). It could also be useful for caching the VM-generated data, between the restarts... Any plans for that? Any hints?

**Comment by grigorye** [comment]
Update: as a workaround for sharing files with startup script, I can `run python -m http.server` on host and `curl` them from VM, but that's a bit cumbersome.

**Comment by fkorotkov** [comment]
I guess we can add a similar `--dir` option for VMs. It will user's responsibility to clean up the data if needed from hosts though. @edigaryev what do you think?
